id = "visual-studio-dark-theme-c-cpp"
name = "Visual Studio Dark Theme C/C++"
version = "0.0.1"
schema_version = 1
authors = ["Tré Dudman"]
description = "Visual Studio Dark C/C++"
repository = "https://github.com/Tremus/visual-studio-dark-theme-zed"